name = "telegram-bot"
type = "javascript"
main = "worker.js"
account_id = "2518a283a31f599487bea84c077e7b97"
workers_dev = true

[env.production]
routes = [
  { pattern = "example.com/*", zone_id = "YOUR_ZONE_ID" }
]
